Repository Goldify/Goldify, pull requests merged in 2020-12, with the labels that each got.

#20 Adds Top Listener Data and re-structures the User Data file tree
  package.json
  src/__test_utils__/GoldifyExecuteTestUtils.js
  src/__test_utils__/TopListeningDataTestUtils.js
  src/__test_utils__/UserInfoTestUtils.js
  src/__tests__/GoldifyExecutePage.test.js
  src/__tests__/execute/GoldifyExecutePage.test.js
  src/__tests__/execute/GoldifyExecuteUtils.test.js
  src/__tests__/execute/top-listens/TopListeningData.test.js
  src/__tests__/execute/top-listens/TopListeningDataUtils.test.js
  src/__tests__/execute/user-info/UserInfo.test.js
  src/__tests__/execute/user-info/UserInfoUtils.test.js
  src/css/GoldifyExecutePage.css
  src/css/TopListeningData.css
  src/css/UserInfo.css
  src/js/execute/GoldifyExecutePage.js
  src/js/execute/top-listens/TopListeningData.js
  src/js/execute/user-info/UserInfo.js
  src/js/utils/GoldifyExecuteUtils.js
  src/js/utils/TopListeningDataUtils.js
  src/js/utils/UserInfoUtils.js
  yarn.lock
Labels: enhancement, refactor

#21 Initial Playlist Functionality
  src/__test_utils__/axiosHelpersTestUtils.js
  src/__test_utils__/playlistTestUtils.js
  src/__test_utils__/playlistTracksTestUtils.js
  src/__tests__/execute/playlist/playlist.test.js
  src/__tests__/execute/playlist/playlistTracks.test.js
  src/__tests__/utils/axiosHelpers.test.js
  src/js/utils/TopListeningDataUtils.js
  src/js/utils/axiosHelpers.js
  src/js/utils/playlist.js
  src/js/utils/playlistTracks.js
Labels: enhancement

#26 Add ability to upload images
  src/__test_utils__/playlistTestUtils.js
  src/__test_utils__/playlistTracksTestUtils.js
  src/__tests__/execute/GoldifyExecuteUtils.test.js
  src/__tests__/utils/playlist.test.js
  src/__tests__/utils/playlistTracks.test.js
  src/assets/goldifyBase64String.js
  src/js/utils/GoldifyExecuteUtils.js
  src/js/utils/playlist.js
Labels: enhancement

#29 Rename directories/tools, add and enforce prettier linting
  .dockerignore
  .eslintrc.js
  .prettierrc
  package.json
  src/__fixtures__/GoldifySoloFixtures.js
  src/__fixtures__/TopListeningDataFixtures.js
  src/__fixtures__/UserInfoFixtures.js
  src/__fixtures__/axiosHelpersFixtures.js
  src/__fixtures__/playlistFixtures.js
  src/__fixtures__/playlistTracksFixtures.js
  src/__test_utils__/axiosHelpersTestUtils.js
  src/__tests__/GoldifyApp.test.js
  src/__tests__/execute/GoldifyExecutePage.test.js
  src/__tests__/execute/top-listens/TopListeningDataUtils.test.js
  src/__tests__/execute/user-info/UserInfoUtils.test.js
  src/__tests__/solo/GoldifySoloPage.test.js
  src/__tests__/solo/GoldifySoloUtils.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylist.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylistData.test.js
  src/__tests__/solo/top-listens/TopListeningData.test.js
  src/__tests__/solo/top-listens/TopListeningDataUtils.test.js
  src/__tests__/solo/user-info/UserInfo.test.js
  src/__tests__/solo/user-info/UserInfoUtils.test.js
  src/__tests__/utils/axiosHelpers.test.js
  src/__tests__/utils/playlist.test.js
  src/__tests__/utils/playlistTracks.test.js
  src/css/GoldifySoloPage.css
  src/index.js
  src/js/GoldifyApp.js
  src/js/execute/goldify-playlist/GoldifyPlaylist.js
  src/js/landing/GoldifyLandingPage.js
  src/js/solo/GoldifySoloPage.js
  src/js/solo/goldify-playlist/GoldifyPlaylist.js
  src/js/solo/goldify-playlist/GoldifyPlaylistData.js
  src/js/solo/top-listens/TopListeningData.js
  src/js/solo/user-info/UserInfo.js
  src/js/utils/GoldifySoloUtils.js
  src/js/utils/UserInfoUtils.js
  src/js/utils/reportWebVitals.js
  src/setupTests.js
  yarn.lock
Labels: enhancement, refactor

#30 Add CreatePlaylist component + small refactor to make this easier
  src/__fixtures__/playlistFixtures.js
  src/__tests__/GoldifyApp.test.js
  src/__tests__/solo/GoldifySoloPage.test.js
  src/__tests__/solo/goldify-playlist/GoldifyCreatePlaylist.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylist.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylistData.test.js
  src/__tests__/solo/user-info/UserInfo.test.js
  src/js/GoldifyApp.js
  src/js/landing/GoldifyLandingPage.js
  src/js/solo/GoldifySoloPage.js
  src/js/solo/goldify-playlist/GoldifyCreatePlaylist.js
  src/js/solo/goldify-playlist/GoldifyPlaylist.js
  src/js/solo/goldify-playlist/GoldifyPlaylistData.js
  src/js/solo/user-info/UserInfo.js
  src/js/utils/UserInfoUtils.js
  src/js/utils/constants.js
Labels: enhancement

#33 Adds new tab panel: Short Term, Medium Term, and Long Term
  Dockerfile.dev
  package.json
  src/__fixtures__/TopListeningDataFixtures.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylistData.test.js
  src/__tests__/solo/top-listens/TopListeningData.test.js
  src/__tests__/solo/top-listens/TopListeningDataUtils.test.js
  src/css/GoldifySoloPage.css
  src/css/TrackDataTable.css
  src/css/UserInfo.css
  src/js/solo/GoldifySoloPage.js
  src/js/solo/goldify-playlist/GoldifyPlaylistData.js
  src/js/solo/top-listens/TopListeningData.js
  src/js/solo/user-info/UserInfo.js
  src/js/utils/TopListeningDataUtils.js
  yarn.lock
Labels: enhancement

#40 auto-fill empty playlists, add lots of comments
  src/__tests__/solo/top-listens/TopListeningData.test.js
  src/js/GoldifyApp.js
  src/js/landing/GoldifyLandingPage.js
  src/js/solo/GoldifySoloPage.js
  src/js/solo/goldify-playlist/GoldifyCreatePlaylist.js
  src/js/solo/goldify-playlist/GoldifyPlaylist.js
  src/js/solo/goldify-playlist/GoldifyPlaylistData.js
  src/js/solo/top-listens/TopListeningData.js
  src/js/solo/user-info/UserInfo.js
  src/js/utils/GoldifySoloUtils.js
  src/js/utils/TopListeningDataUtils.js
  src/js/utils/UserInfoUtils.js
  src/js/utils/axiosHelpers.js
  src/js/utils/constants.js
  src/js/utils/playlist.js
  src/js/utils/playlistTracks.js
  src/js/utils/reportWebVitals.js
Labels: documentation, enhancement

#42 Revamps UI to be more reactive, as well as test updates
  src/__tests__/GoldifyApp.test.js
  src/__tests__/solo/top-listens/TopListeningData.test.js
  src/__tests__/solo/user-info/UserInfo.test.js
  src/assets/spotify_logo.png
  src/assets/spotify_logo_white.png
  src/css/GoldifyApp.css
  src/css/GoldifySoloPage.css
  src/css/TrackDataTable.css
  src/css/UserInfo.css
  src/css/index.css
  src/js/GoldifyApp.js
  src/js/solo/goldify-playlist/GoldifyPlaylistData.js
  src/js/solo/top-listens/TopListeningData.js
  src/js/solo/user-info/UserInfo.js
  src/js/utils/constants.js
Labels: ui-update

#43 Fixes issue with Cancel button where after one use it would no longer work as intended
  src/js/solo/goldify-playlist/GoldifyPlaylistData.js
Labels: bug

#45 Adds ability to move tracks up and down within the Goldify Playlist table
  package.json
  src/__tests__/solo/goldify-playlist/GoldifyPlaylistData.test.js
  src/index.js
  src/js/solo/goldify-playlist/GoldifyPlaylistData.js
  src/js/utils/GoldifyPlaylistDataElements.js
  yarn.lock
Labels: enhancement

#46 Adds new two table UI, and other UI changes, when using Goldify in the Desktop view
  src/css/TrackDataTable.css
  src/js/solo/top-listens/TopListeningData.js
Labels: enhancement, ui-update
