Repository Goldify/Goldify, pull requests merged in 2021-01, with the labels that each got.

#50 Changes .js extension to .jsx extension for React files
  src/__tests__/GoldifyApp.test.js
  src/index.jsx
  src/js/GoldifyApp.jsx
  src/js/landing/GoldifyLandingPage.jsx
  src/js/solo/GoldifySoloPage.jsx
  src/js/solo/goldify-playlist/GoldifyCreatePlaylist.jsx
  src/js/solo/goldify-playlist/GoldifyPlaylist.jsx
  src/js/solo/goldify-playlist/GoldifyPlaylistData.jsx
  src/js/solo/top-listens/TopListeningData.jsx
  src/js/solo/user-info/UserInfo.jsx
Labels: refactor

#54 Adds links to Spotify, as well as to Goldify playlist, around the application
  src/__fixtures__/TopListeningDataFixtures.js
  src/__fixtures__/playlistTracksFixtures.js
  src/__tests__/solo/GoldifySoloUtils.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylistData.test.js
  src/__tests__/solo/top-listens/TopListeningData.test.js
  src/assets/spotify_full_logo_black.png
  src/css/GoldifyApp.css
  src/css/GoldifySoloPage.css
  src/js/GoldifyApp.jsx
  src/js/solo/goldify-playlist/GoldifyPlaylistData.jsx
  src/js/solo/top-listens/TopListeningData.jsx
  src/js/utils/GoldifyPlaylistDataElements.js
  src/js/utils/GoldifySoloUtils.js
  src/js/utils/constants.js
Labels: brand-guidelines, enhancement

#53 Makes the entire User Info widget clickable, redirecting to user's Spotify profile
  src/__tests__/solo/user-info/UserInfo.test.js
  src/css/UserInfo.css
  src/js/solo/user-info/UserInfo.jsx
Labels: enhancement

#49 Replaces old Goldify Logo with new (fresh) logo in all applicable places
  public/favicon.ico
  public/goldify_logo.png
  src/assets/goldify_logo.png
  src/assets/new_goldify_logo.png
  src/assets/spotify_logo_white.png
Labels: enhancement, ui-update

#55 uploads playlist image after playlist creation
  src/__tests__/solo/goldify-playlist/GoldifyCreatePlaylist.test.js
  src/assets/goldifyBase64String.js
  src/js/solo/goldify-playlist/GoldifyCreatePlaylist.jsx
Labels: enhancement

#56 Adds new notification in place of the old alert for recommended song autofill
  package.json
  src/__tests__/solo/GoldifySoloPage.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylist.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylistData.test.js
  src/__tests__/solo/top-listens/TopListeningData.test.js
  src/css/GoldifySoloPage.css
  src/css/TrackDataTable.css
  src/js/solo/GoldifySoloPage.jsx
  src/js/solo/goldify-playlist/GoldifyPlaylist.jsx
  src/js/solo/goldify-playlist/GoldifyPlaylistData.jsx
  src/js/solo/top-listens/TopListeningData.jsx
  yarn.lock
Labels: bug, enhancement

#59 Replaces Goldify Playlist creation alerts with a popup the user must click through
  src/__tests__/solo/goldify-playlist/GoldifyCreatePlaylist.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylist.test.js
  src/css/GoldifyCreatePlaylist.css
  src/css/UserInfo.css
  src/js/solo/goldify-playlist/GoldifyCreatePlaylist.jsx
  src/js/solo/goldify-playlist/GoldifyPlaylist.jsx
Labels: enhancement, ui-update

#67 Adds GitHub icon landing page
  src/__tests__/GoldifyApp.test.js
  src/__tests__/landing/GoldifyLandingPage.test.js
  src/assets/github_icon_white.jpg
  src/css/GoldifyLandingPage.css
  src/js/landing/GoldifyLandingPage.jsx
  src/js/utils/constants.js
Labels: enhancement

#69 Glue footer to the bottom of the page
  src/__tests__/GoldifyApp.test.js
  src/assets/spotify_full_logo_white.png
  src/css/GoldifyApp.css
  src/css/GoldifyLandingPage.css
  src/css/GoldifySoloPage.css
  src/css/TrackDataTable.css
  src/css/index.css
  src/js/GoldifyApp.jsx
Labels: ui-update
