Repository Goldify/Goldify, pull requests merged in 2021-03, with the labels that each got.

#74 Updates create-react-app 4.0.3 which updates immer to 8.0.1
  package.json
  yarn.lock
Labels: security

#75 Adds new tab for Recently Removed songs
  src/__tests__/solo/goldify-playlist/GoldifyPlaylistData.test.js
  src/__tests__/solo/top-listens/TopListeningData.test.js
  src/js/solo/goldify-playlist/GoldifyPlaylistData.jsx
  src/js/solo/top-listens/TopListeningData.jsx
  src/js/utils/constants.js
Labels: enhancement

#76 Wrapping up final changes before Goldify 1.0
  .github/workflows/main.yml
  README.md
  src/__tests__/solo/GoldifySoloPage.test.js
  src/__tests__/solo/goldify-playlist/GoldifyCreatePlaylist.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylist.test.js
  src/__tests__/solo/goldify-playlist/GoldifyPlaylistData.test.js
  src/__tests__/solo/top-listens/TopListeningData.test.js
  src/css/GoldifyApp.css
  src/js/GoldifyApp.jsx
  src/js/landing/GoldifyLandingPage.jsx
  src/js/solo/GoldifySoloPage.jsx
  src/js/solo/goldify-playlist/GoldifyCreatePlaylist.jsx
  src/js/solo/goldify-playlist/GoldifyPlaylist.jsx
  src/js/solo/goldify-playlist/GoldifyPlaylistData.jsx
  src/js/solo/top-listens/TopListeningData.jsx
  src/js/solo/user-info/UserInfo.jsx
  src/js/utils/constants.js
  src/js/utils/playlist.js
Labels: bug, enhancement

#78 Use default goldify logo if no user profile picture
  src/__tests__/solo/user-info/UserInfo.test.js
  src/js/solo/user-info/UserInfo.jsx
Labels: bug

#79 Adds Badges to readme
  README.md
Labels: documentation, enhancement
